media_library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path("movies/", include('movies.urls')),
    path("tvseries/", include('tvseries.urls')),
]

movies/urls.py
from django.urls import path
from .views import FolderAddView, MovieListView, MovieDetailView, VideoPlayerView
from .views import addFolder, playVideo

app_name = 'movies'
urlpatterns = [
    path("", MovieListView.as_view(), name="movie_list"),
    path("addFTP/", FolderAddView.as_view(), name="addFTP"),
    path("ajax/addFTP/", addFolder, name="ajax_addFTP"),
    path("<pk>/", MovieDetailView.as_view(), name="movie_detail"),
    path("play/<path:urlPath>", playVideo, name="playVideo"),
    path("playing/<path:urlPath>", VideoPlayerView.as_view(), name="video_player"),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home")
]

tvseries/urls.py
from django.urls import path
from .views import TvListView, TvDetailView, addFolder, FolderAddView, playVideo, VideoPlayerView

app_name = 'tvseries'
urlpatterns = [
    path("", TvListView.as_view(), name="tv_list"),
    path("addFTP/", FolderAddView.as_view(), name="addFTP"),
    path("ajax/addFTP", addFolder, name="ajax_addFTP"),
    path("<pk>/", TvDetailView.as_view(), name="tv_detail"),
    path("play/<path:urlPath>", playVideo, name="playVideo"),
    path("playing/<path:urlPath>", VideoPlayerView.as_view(), name="video_player"),
]

templates/folderAddMovie.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Moviesearch</title>
	<link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
		integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/folderAddMovie.css' %}">

	<script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>

<body>
	<div class="tint">
		<form action="{% url 'movies:ajax_addFTP' %}" method="post">
			{% csrf_token %}
			<div class="login-box">

				<h3>Add Movie Server</h3>
				<div class="textbox">
					<i class="fas fa-user"></i>
					<input type="text" placeholder="IP address" name="ip_address" value="" required>
				</div>

				<div class="textbox">
					<i class="fas fa-lock"></i>
					<input type="text" placeholder="Port no." name="port" value="" required>
				</div>
				<span>
					<input class="btn" type="submit" value="Submit">
					<a href="{% url 'movies:movie_list' %}" class="btn" type="button" name="back" value="back">Go
						back</a>
				</span>
			</div>
		</form>

	</div>
	<!------------------------------------------------------JS---------------------------------------------->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
		integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous">
	</script>
</body>

</html>

templates/folderAddTV.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Moviesearch</title>
 <link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static '/css/folderAddTV.css' %}">

  <script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>
<body>
	<div class="tint">
		<form method="post" action="{% url 'tvseries:ajax_addFTP' %}">
		{% csrf_token %}
		<div class="login-box">

			<h3>Add series server</h3>
			<div class="textbox">
				<i class="fas fa-user"></i>
				<input type="text" placeholder="IP address" name="ip_address" value="" required>
			</div>

			<div class="textbox">
				<i class="fas fa-lock"></i>
				<input type="text" placeholder="Port no." name="port" value="" required>
			</div>
			<span>
			<input class="btn" type="submit" value="Submit">
    		<a href="{% url 'tvseries:tv_list' %}" class="btn" type="button" name="back" value="back">Go back</a>
			</span>
		</div>
		</form>

	</div>
<!------------------------------------------------------JS---------------------------------------------->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>

templates/movie_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Movie Info Page</title>
	<link rel="stylesheet" href="	https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/movie_detail.css' %}">
	<script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>
<body>
<!----------------------------------------navbar------------------------------------------------------------------->

	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#"><i class="fas fa-film"></i> MediaLib</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Sign out <i class="fas fa-sign-out-alt"></i></a></li>
	      </ul>
	      <form class="navbar-form navbar-right">
	        <!--<div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Go</button>-->
	      </form>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<!------------------------------------------Line break---------------------------------------------------------------->
<br><br><br><br>
<!--------------------------------------------------------Jumbotron--------------------------------------------------->

	<div class="container">
		<div class="jumbotron">
			<div class="row">
				<div id="content">
					<!------------------------------cards------------------------------------------------>
					<div class="col-lg-4">
						<div class="thumbnail">
							<img src="{{metadata.poster}}">
						</div>
					</div>
					<!------------------------------cards------------------------------------------------>
					<div class="col-lg-8">
						<h2>{{object.name}}</h2><br>
						<h4>Year:</h4><span>{{metadata.year}}</span><br>
						<h4>Genre:</h4><span>{{genres}}</span><br>
						<h4>Description:</h4>
						<span>{{metadata.description}}</span><br>
						<h4>Rating:</h4><span>{{metadata.rating}}</span><br><br>
						<a href="{% url 'movies:playVideo' object.urlPath %}?movieid={{object.media_id}}" type="button" class="btn btn-default btn-lg" id="series"><i class="fas fa-play"></i>  Play</a>
					</div>
				</div>
			</div>
		</div>
	</div>
		
<!------------------------------------------------------JS----------------------------------------------------------->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>

templates/movie_list.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Movies</title>
	<link rel="stylesheet" href="	https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
		integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/movie_list.css' %}">
	<script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>

<body>
	<!----------------------------------------navbar--------------------------------------------------------------------->

	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><i class="fas fa-film"></i> MediaLib</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'logout' %}">Sign out <i class="fas fa-sign-out-alt"></i></a></li>
				</ul>
				<form class="navbar-form navbar-right">
					<!--<div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>-->
					<a href="{% url 'movies:addFTP' %}" type="button" class="btn btn-default">+ FTP Server</a>
				</form>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	<!--------------------------------------------Movie and tv series buttons-------------------------------------------->

	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-sm-12 col-xs-12">
				<a href="{% url 'movies:movie_list' %}" type="button" class="btn btn-default btn-lg"
					id="movies">Movies</a>
			</div>
			<div class="col-lg-6 col-sm-12 col-xs-12">
				<a href="{% url 'tvseries:tv_list' %}" type="button" class="btn btn-default btn-lg" id="series">TV
					Series</a>
			</div>
		</div>
	</div>
	</div>
	<!-----------------------------------------------------Movie cards--------------------------------------------------->

	<div class="container">
		<div class="row">
			<div id="content">
				<!------------------------------cards------------------------------------------------>
				{% for movie in movie_list %}
				<div class="col-lg-3 col-sm-6">
					<div class="thumbnail">
						<img src="{{movie.poster}}">
						<div class="caption">
							<h4>{{movie.name}}</h4>
							<p id="cardbtn">
								<a href="#" class="btn btn-primary" role="button"><i class="fas fa-play"></i> Play</a>
								<a href="{% url 'movies:movie_detail' movie.pk %}" class="btn btn-default"
									role="button"><i class="fas fa-info-circle"></i> Details</a>
							</p>
						</div>
					</div>
				</div>


				{% endfor %}
				<!------------------------------cards------------------------------------------------>

			</div>
		</div>
	</div>

	<!----------------------------------------pagenation--------------------------------------------->
	<div class="container">
		<div class="pageno">
			<nav aria-label="Page navigation">
				<ul class="pagination">
					<li>
						<a href="#" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						</a>
					</li>
					<li class="active"><a href="#">1</a></li>
					<li>
						<a href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
				</ul>
			</nav>
		</div>
	</div>

	<!------------------------------------------------------JS----------------------------------------------------------->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
		integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous">
	</script>
</body>

</html>

templates/movievideoplayer.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>Video player</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static '/css/movievideoplayer.css' %}">
  <script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>

<body>
  <div class="tint">
    <!-- navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><i class="fas fa-film"></i> MediaLib</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'movies:movie_list' %}">Movies</a></li>
            <li><a href="{% url 'tvseries:tv_list' %}">TV shows</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'logout' %}">Sign out <i class="fas fa-sign-out-alt"></i></a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <!-- video player -->
    <div class="container">
      <div class="jumbotron">
        <video src="{{urlPath}}" controls width="320" height="240">
          <a href="{{urlPath}}">Download song</a>
        </video>
        <!--
        <video controls>
          <source src="{{urlPath}}" type="video/mp4">
        </video>
        -->
      </div>
    </div>
  </div>
  <!------------------------------------------------------JS----------------------------------------------------------->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
    integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous">
  </script>
</body>

</html>

templates/tv_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Series Info Page</title>
	<link rel="stylesheet" href="	https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/tv_detail.css' %}">
	<script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>
<body>
<!----------------------------------------navbar------------------------------------------------------------------->

	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'movies:movie_list' %}"><i class="fas fa-film"></i> Brand</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="{% url 'logout' %}">Sign out <i class="fas fa-sign-out-alt"></i></a></li>
	      </ul>
	      <form class="navbar-form navbar-right">
		  <!--
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Go</button>
			-->
	      </form>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<!------------------------------------------Line break---------------------------------------------------------------->
<br><br><br><br>
<!--------------------------------------------------------Jumbotron--------------------------------------------------->

	<div class="container">
		<div class="jumbotron">
			<div class="row">
				<div id="content">
					<!------------------------------cards------------------------------------------------>
					<div class="col-lg-4">
						<div class="thumbnail">
							<img src="{{metadata.poster}}">
						</div>
					</div>
					<!------------------------------cards------------------------------------------------>
					<div class="col-lg-8">
						<h2>{{object.name}}</h2><br>
						<h4>Year:</h4><span>{{metadata.year}}</span><br>
						<h4>Genre:</h4><span>Comedy, Mystery</span><br>
						<h4>Description:</h4>
						<span>{{metadata.description}}</span><br>
						<h4>Rating:</h4><span>{{metadata.rating}}</span><br><br>
						
					</div>
				</div>
			</div>
			<br><br>
			<hr>
			<br>
			<h2>Episodes</h2>
			<br>
			<div class="row">
				<div id="content">
					<!-- repeat this line from here-------------------------------------------------------------------------------------- -->
					{% for ep in episodes %}
					<div class="col-lg-4">
						<a href="{% url 'tvseries:playVideo' ep.urlPath %}?tvid={{object.media_id}}" type="button" class="btn btn-default btn-sm" id="series"><i class="fas fa-play"></i>{{ep.name}}</a>
					</div>
					{% endfor %}
					<!------------------------------to here------------------------------------------------------------------------>
		</div>
	</div>
		
<!------------------------------------------------------JS----------------------------------------------------------->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>

templates/tv_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>TV shows</title>
	<link rel="stylesheet" href="	https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/tv_list.css' %}">
	<script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>
<body>
<!----------------------------------------navbar--------------------------------------------------------------------->

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'tvseries:tv_list' %}"><i class="fas fa-film"></i> MediaLib</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout' %}">Sign out <i class="fas fa-sign-out-alt"></i></a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <!--<div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>-->
        <a href="{% url 'tvseries:addFTP' %}" type="button" class="btn btn-default">+ FTP Server</a>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--------------------------------------------Movie and tv series buttons-------------------------------------------->

	<div class="container">
		<div class="row">
				<div class="col-lg-6 col-sm-12 col-xs-12">
					<a href="{% url 'movies:movie_list' %}" type="button" class="btn btn-default btn-lg" id="movies">Movies</a>
				</div>
				<div class="col-lg-6 col-sm-12 col-xs-12">
					<button type="button" class="btn btn-default btn-lg" id="series">TV Series</button>
				</div>
			</div>
		</div>
	</div>
<!-----------------------------------------------------Movie cards--------------------------------------------------->

	<div class="container">
		<div class="row">
			<div id="content">
				<!------------------------------cards------------------------------------------------>
				{% for show in tv_list %}
				<div class="col-lg-3 col-sm-6">
					<div class="thumbnail">
						<img src="{{show.poster}}">
						<div class="caption">
        					<h4>{{show.name}}</h4>
        					<p id="cardbtn">
        						<a href="#" class="btn btn-primary" role="button"><i class="fas fa-play"></i> Play</a> 
        						<a href="{% url 'tvseries:tv_detail' show.pk %}" class="btn btn-default" role="button"><i class="fas fa-info-circle"></i> Details</a>
        					</p>
      					</div>
					</div>
				</div>
				{% endfor %}
				<!------------------------------cards------------------------------------------------>
				
				
				
				
			</div>
		</div>
	</div>

	<!----------------------------------------pagenation--------------------------------------------->
	<div class="container">
		<div class="pageno">
			<nav aria-label="Page navigation">
		  		<ul class="pagination">
		    		<li>
		      			<a href="#" aria-label="Previous">
		        			<span aria-hidden="true">&laquo;</span>
		      			</a>
		    		</li>
		    		<li class="active"><a href="#">1</a></li>
		    		<li>
		      			<a href="#" aria-label="Next">
		        			<span aria-hidden="true">&raquo;</span>
		      			</a>
		    		</li>
		  		</ul>
			</nav>
		</div>
	</div>

<!------------------------------------------------------JS----------------------------------------------------------->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>

templates/tvvideoplayer.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Video player</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static '/css/tvvideoplayer.css' %}">
	<script src="https://kit.fontawesome.com/7fa4b450dd.js" crossorigin="anonymous"></script>
</head>
<body>
	<div class="tint">
	<!-- navbar -->
	<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'movies:movie_list' %}" class="navbar-brand" href="#"><i class="fas fa-film"></i> MediaLib</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'movies:movie_list' %}">Movies:w</a></li>
        <li><a href="{% url 'tvseries:tv_list' %}">TV shows</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout' %}">Sign out <i class="fas fa-sign-out-alt"></i></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- video player -->
<div class="container">
	<div class="jumbotron">
	<video controls>
		<source src="{{urlPath}}" type="video/mp4">
	</video>
	</div>
</div>
</div>
	<!------------------------------------------------------JS----------------------------------------------------------->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>